/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ChequeData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2497026834253436642L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChequeData\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"fields\":[{\"name\":\"cheque\",\"type\":{\"type\":\"record\",\"name\":\"Cheque\",\"fields\":[{\"name\":\"numeroCheque\",\"type\":\"string\",\"example\":\"1234567\"},{\"name\":\"nombreBeneficiario\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"127\",\"minLength\":3,\"maxLength\":3},{\"name\":\"claveBanco\",\"type\":\"string\",\"example\":\"127\",\"minLength\":3,\"maxLength\":3},{\"name\":\"tipoCheque\",\"type\":\"string\",\"example\":\"127\",\"minLength\":3,\"maxLength\":3}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ChequeData> ENCODER =
      new BinaryMessageEncoder<ChequeData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ChequeData> DECODER =
      new BinaryMessageDecoder<ChequeData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ChequeData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ChequeData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ChequeData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ChequeData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ChequeData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ChequeData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ChequeData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ChequeData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private mx.baz.avro.model.liabilities.Cheque cheque;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ChequeData() {}

  /**
   * All-args constructor.
   * @param cheque The new value for cheque
   */
  public ChequeData(mx.baz.avro.model.liabilities.Cheque cheque) {
    this.cheque = cheque;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cheque;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cheque = (mx.baz.avro.model.liabilities.Cheque)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cheque' field.
   * @return The value of the 'cheque' field.
   */
  public mx.baz.avro.model.liabilities.Cheque getCheque() {
    return cheque;
  }


  /**
   * Sets the value of the 'cheque' field.
   * @param value the value to set.
   */
  public void setCheque(mx.baz.avro.model.liabilities.Cheque value) {
    this.cheque = value;
  }

  /**
   * Creates a new ChequeData RecordBuilder.
   * @return A new ChequeData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.ChequeData.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.ChequeData.Builder();
  }

  /**
   * Creates a new ChequeData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ChequeData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.ChequeData.Builder newBuilder(mx.baz.avro.model.liabilities.ChequeData.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.ChequeData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.ChequeData.Builder(other);
    }
  }

  /**
   * Creates a new ChequeData RecordBuilder by copying an existing ChequeData instance.
   * @param other The existing instance to copy.
   * @return A new ChequeData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.ChequeData.Builder newBuilder(mx.baz.avro.model.liabilities.ChequeData other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.ChequeData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.ChequeData.Builder(other);
    }
  }

  /**
   * RecordBuilder for ChequeData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChequeData>
    implements org.apache.avro.data.RecordBuilder<ChequeData> {

    private mx.baz.avro.model.liabilities.Cheque cheque;
    private mx.baz.avro.model.liabilities.Cheque.Builder chequeBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.ChequeData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cheque)) {
        this.cheque = data().deepCopy(fields()[0].schema(), other.cheque);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasChequeBuilder()) {
        this.chequeBuilder = mx.baz.avro.model.liabilities.Cheque.newBuilder(other.getChequeBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ChequeData instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.ChequeData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.cheque)) {
        this.cheque = data().deepCopy(fields()[0].schema(), other.cheque);
        fieldSetFlags()[0] = true;
      }
      this.chequeBuilder = null;
    }

    /**
      * Gets the value of the 'cheque' field.
      * @return The value.
      */
    public mx.baz.avro.model.liabilities.Cheque getCheque() {
      return cheque;
    }


    /**
      * Sets the value of the 'cheque' field.
      * @param value The value of 'cheque'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.ChequeData.Builder setCheque(mx.baz.avro.model.liabilities.Cheque value) {
      validate(fields()[0], value);
      this.chequeBuilder = null;
      this.cheque = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cheque' field has been set.
      * @return True if the 'cheque' field has been set, false otherwise.
      */
    public boolean hasCheque() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'cheque' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.Cheque.Builder getChequeBuilder() {
      if (chequeBuilder == null) {
        if (hasCheque()) {
          setChequeBuilder(mx.baz.avro.model.liabilities.Cheque.newBuilder(cheque));
        } else {
          setChequeBuilder(mx.baz.avro.model.liabilities.Cheque.newBuilder());
        }
      }
      return chequeBuilder;
    }

    /**
     * Sets the Builder instance for the 'cheque' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.ChequeData.Builder setChequeBuilder(mx.baz.avro.model.liabilities.Cheque.Builder value) {
      clearCheque();
      chequeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cheque' field has an active Builder instance
     * @return True if the 'cheque' field has an active Builder instance
     */
    public boolean hasChequeBuilder() {
      return chequeBuilder != null;
    }

    /**
      * Clears the value of the 'cheque' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.ChequeData.Builder clearCheque() {
      cheque = null;
      chequeBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ChequeData build() {
      try {
        ChequeData record = new ChequeData();
        if (chequeBuilder != null) {
          try {
            record.cheque = this.chequeBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("cheque"));
            throw e;
          }
        } else {
          record.cheque = fieldSetFlags()[0] ? this.cheque : (mx.baz.avro.model.liabilities.Cheque) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ChequeData>
    WRITER$ = (org.apache.avro.io.DatumWriter<ChequeData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ChequeData>
    READER$ = (org.apache.avro.io.DatumReader<ChequeData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.cheque.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.cheque == null) {
        this.cheque = new mx.baz.avro.model.liabilities.Cheque();
      }
      this.cheque.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.cheque == null) {
            this.cheque = new mx.baz.avro.model.liabilities.Cheque();
          }
          this.cheque.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










