/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class datosAdicionales extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8145359314266031807L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"datosAdicionales\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"fields\":[{\"name\":\"anexo\",\"type\":[{\"type\":\"record\",\"name\":\"ChequeData\",\"fields\":[{\"name\":\"cheque\",\"type\":{\"type\":\"record\",\"name\":\"Cheque\",\"fields\":[{\"name\":\"numeroCheque\",\"type\":\"string\",\"example\":\"1234567\"},{\"name\":\"nombreBeneficiario\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"127\",\"minLength\":3,\"maxLength\":3},{\"name\":\"claveBanco\",\"type\":\"string\",\"example\":\"127\",\"minLength\":3,\"maxLength\":3},{\"name\":\"tipoCheque\",\"type\":\"string\",\"example\":\"127\",\"minLength\":3,\"maxLength\":3}]}}]},{\"type\":\"record\",\"name\":\"SPEIData\",\"fields\":[{\"name\":\"spei\",\"type\":{\"type\":\"record\",\"name\":\"SPEI\",\"fields\":[{\"name\":\"nombre\",\"type\":\"string\",\"example\":\"100000001\",\"minLength\":9,\"maxLength\":9},{\"name\":\"numeroCuenta\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"claveBanco\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"tipoCuenta\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"claveRastreo\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"referenciaCobro\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"100000001\"}]}}]},{\"type\":\"record\",\"name\":\"TransferData\",\"fields\":[{\"name\":\"transferencia\",\"type\":{\"type\":\"record\",\"name\":\"Transferencia\",\"fields\":[{\"name\":\"nombre\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"Alberto Garcia\"},{\"name\":\"numeroCuenta\",\"type\":\"string\",\"example\":\"1234567\"},{\"name\":\"tipoCuenta\",\"type\":\"string\",\"example\":\"02\"}]}}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<datosAdicionales> ENCODER =
      new BinaryMessageEncoder<datosAdicionales>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<datosAdicionales> DECODER =
      new BinaryMessageDecoder<datosAdicionales>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<datosAdicionales> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<datosAdicionales> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<datosAdicionales> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<datosAdicionales>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this datosAdicionales to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a datosAdicionales from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a datosAdicionales instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static datosAdicionales fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Object anexo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public datosAdicionales() {}

  /**
   * All-args constructor.
   * @param anexo The new value for anexo
   */
  public datosAdicionales(java.lang.Object anexo) {
    this.anexo = anexo;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return anexo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: anexo = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'anexo' field.
   * @return The value of the 'anexo' field.
   */
  public java.lang.Object getAnexo() {
    return anexo;
  }


  /**
   * Sets the value of the 'anexo' field.
   * @param value the value to set.
   */
  public void setAnexo(java.lang.Object value) {
    this.anexo = value;
  }

  /**
   * Creates a new datosAdicionales RecordBuilder.
   * @return A new datosAdicionales RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.datosAdicionales.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.datosAdicionales.Builder();
  }

  /**
   * Creates a new datosAdicionales RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new datosAdicionales RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.datosAdicionales.Builder newBuilder(mx.baz.avro.model.liabilities.datosAdicionales.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.datosAdicionales.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.datosAdicionales.Builder(other);
    }
  }

  /**
   * Creates a new datosAdicionales RecordBuilder by copying an existing datosAdicionales instance.
   * @param other The existing instance to copy.
   * @return A new datosAdicionales RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.datosAdicionales.Builder newBuilder(mx.baz.avro.model.liabilities.datosAdicionales other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.datosAdicionales.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.datosAdicionales.Builder(other);
    }
  }

  /**
   * RecordBuilder for datosAdicionales instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<datosAdicionales>
    implements org.apache.avro.data.RecordBuilder<datosAdicionales> {

    private java.lang.Object anexo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.datosAdicionales.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.anexo)) {
        this.anexo = data().deepCopy(fields()[0].schema(), other.anexo);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing datosAdicionales instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.datosAdicionales other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.anexo)) {
        this.anexo = data().deepCopy(fields()[0].schema(), other.anexo);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'anexo' field.
      * @return The value.
      */
    public java.lang.Object getAnexo() {
      return anexo;
    }


    /**
      * Sets the value of the 'anexo' field.
      * @param value The value of 'anexo'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.datosAdicionales.Builder setAnexo(java.lang.Object value) {
      validate(fields()[0], value);
      this.anexo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'anexo' field has been set.
      * @return True if the 'anexo' field has been set, false otherwise.
      */
    public boolean hasAnexo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'anexo' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.datosAdicionales.Builder clearAnexo() {
      anexo = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public datosAdicionales build() {
      try {
        datosAdicionales record = new datosAdicionales();
        record.anexo = fieldSetFlags()[0] ? this.anexo :  defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<datosAdicionales>
    WRITER$ = (org.apache.avro.io.DatumWriter<datosAdicionales>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<datosAdicionales>
    READER$ = (org.apache.avro.io.DatumReader<datosAdicionales>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










