/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SPEIData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7996050425712739812L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SPEIData\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"fields\":[{\"name\":\"spei\",\"type\":{\"type\":\"record\",\"name\":\"SPEI\",\"fields\":[{\"name\":\"nombre\",\"type\":\"string\",\"example\":\"100000001\",\"minLength\":9,\"maxLength\":9},{\"name\":\"numeroCuenta\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"claveBanco\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"tipoCuenta\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"claveRastreo\",\"type\":\"string\",\"example\":\"100000001\"},{\"name\":\"referenciaCobro\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"100000001\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SPEIData> ENCODER =
      new BinaryMessageEncoder<SPEIData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SPEIData> DECODER =
      new BinaryMessageDecoder<SPEIData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SPEIData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SPEIData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SPEIData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SPEIData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SPEIData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SPEIData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SPEIData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SPEIData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private mx.baz.avro.model.liabilities.SPEI spei;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SPEIData() {}

  /**
   * All-args constructor.
   * @param spei The new value for spei
   */
  public SPEIData(mx.baz.avro.model.liabilities.SPEI spei) {
    this.spei = spei;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return spei;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: spei = (mx.baz.avro.model.liabilities.SPEI)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'spei' field.
   * @return The value of the 'spei' field.
   */
  public mx.baz.avro.model.liabilities.SPEI getSpei() {
    return spei;
  }


  /**
   * Sets the value of the 'spei' field.
   * @param value the value to set.
   */
  public void setSpei(mx.baz.avro.model.liabilities.SPEI value) {
    this.spei = value;
  }

  /**
   * Creates a new SPEIData RecordBuilder.
   * @return A new SPEIData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.SPEIData.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.SPEIData.Builder();
  }

  /**
   * Creates a new SPEIData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SPEIData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.SPEIData.Builder newBuilder(mx.baz.avro.model.liabilities.SPEIData.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.SPEIData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.SPEIData.Builder(other);
    }
  }

  /**
   * Creates a new SPEIData RecordBuilder by copying an existing SPEIData instance.
   * @param other The existing instance to copy.
   * @return A new SPEIData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.SPEIData.Builder newBuilder(mx.baz.avro.model.liabilities.SPEIData other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.SPEIData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.SPEIData.Builder(other);
    }
  }

  /**
   * RecordBuilder for SPEIData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SPEIData>
    implements org.apache.avro.data.RecordBuilder<SPEIData> {

    private mx.baz.avro.model.liabilities.SPEI spei;
    private mx.baz.avro.model.liabilities.SPEI.Builder speiBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.SPEIData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.spei)) {
        this.spei = data().deepCopy(fields()[0].schema(), other.spei);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasSpeiBuilder()) {
        this.speiBuilder = mx.baz.avro.model.liabilities.SPEI.newBuilder(other.getSpeiBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing SPEIData instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.SPEIData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.spei)) {
        this.spei = data().deepCopy(fields()[0].schema(), other.spei);
        fieldSetFlags()[0] = true;
      }
      this.speiBuilder = null;
    }

    /**
      * Gets the value of the 'spei' field.
      * @return The value.
      */
    public mx.baz.avro.model.liabilities.SPEI getSpei() {
      return spei;
    }


    /**
      * Sets the value of the 'spei' field.
      * @param value The value of 'spei'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.SPEIData.Builder setSpei(mx.baz.avro.model.liabilities.SPEI value) {
      validate(fields()[0], value);
      this.speiBuilder = null;
      this.spei = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'spei' field has been set.
      * @return True if the 'spei' field has been set, false otherwise.
      */
    public boolean hasSpei() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'spei' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.SPEI.Builder getSpeiBuilder() {
      if (speiBuilder == null) {
        if (hasSpei()) {
          setSpeiBuilder(mx.baz.avro.model.liabilities.SPEI.newBuilder(spei));
        } else {
          setSpeiBuilder(mx.baz.avro.model.liabilities.SPEI.newBuilder());
        }
      }
      return speiBuilder;
    }

    /**
     * Sets the Builder instance for the 'spei' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.SPEIData.Builder setSpeiBuilder(mx.baz.avro.model.liabilities.SPEI.Builder value) {
      clearSpei();
      speiBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'spei' field has an active Builder instance
     * @return True if the 'spei' field has an active Builder instance
     */
    public boolean hasSpeiBuilder() {
      return speiBuilder != null;
    }

    /**
      * Clears the value of the 'spei' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.SPEIData.Builder clearSpei() {
      spei = null;
      speiBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SPEIData build() {
      try {
        SPEIData record = new SPEIData();
        if (speiBuilder != null) {
          try {
            record.spei = this.speiBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("spei"));
            throw e;
          }
        } else {
          record.spei = fieldSetFlags()[0] ? this.spei : (mx.baz.avro.model.liabilities.SPEI) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SPEIData>
    WRITER$ = (org.apache.avro.io.DatumWriter<SPEIData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SPEIData>
    READER$ = (org.apache.avro.io.DatumReader<SPEIData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.spei.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.spei == null) {
        this.spei = new mx.baz.avro.model.liabilities.SPEI();
      }
      this.spei.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.spei == null) {
            this.spei = new mx.baz.avro.model.liabilities.SPEI();
          }
          this.spei.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










