/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This Schema describes about... */
@org.apache.avro.specific.AvroGenerated
public class TransactionCaptacion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8780121646120124732L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionCaptacion\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"doc\":\"This Schema describes about...\",\"fields\":[{\"name\":\"captacion\",\"type\":{\"type\":\"record\",\"name\":\"TransactionCaptacionData\",\"doc\":\"Arreglo de datos para captacion\",\"fields\":[{\"name\":\"idCliente\",\"type\":\"string\",\"example\":\"100000001\",\"minLength\":9,\"maxLength\":9},{\"name\":\"idTipoCliente\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoEmpresa\",\"type\":\"int\",\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoRelacionEmpresa\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idSubSector\",\"type\":\"int\",\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"idNacionalidad\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoDias\",\"type\":\"int\",\"example\":0,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoMeses\",\"type\":\"int\",\"example\":36,\"minLength\":1,\"maxLength\":2},{\"name\":\"concepto\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"100000001\"},{\"name\":\"codigoProductoOriginacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"AM001\"},{\"name\":\"cuentaOriginacion\",\"type\":\"string\",\"example\":\"9674319836\",\"minLength\":10,\"maxLength\":10},{\"name\":\"folioConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"000001\",\"minLength\":2,\"maxLength\":2},{\"name\":\"fechaConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"20200216\",\"minLength\":8,\"maxLength\":8},{\"name\":\"statusConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"1\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionCaptacion> ENCODER =
      new BinaryMessageEncoder<TransactionCaptacion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionCaptacion> DECODER =
      new BinaryMessageDecoder<TransactionCaptacion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionCaptacion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionCaptacion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionCaptacion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionCaptacion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionCaptacion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionCaptacion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionCaptacion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionCaptacion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private mx.baz.avro.model.liabilities.TransactionCaptacionData captacion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionCaptacion() {}

  /**
   * All-args constructor.
   * @param captacion The new value for captacion
   */
  public TransactionCaptacion(mx.baz.avro.model.liabilities.TransactionCaptacionData captacion) {
    this.captacion = captacion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return captacion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: captacion = (mx.baz.avro.model.liabilities.TransactionCaptacionData)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'captacion' field.
   * @return The value of the 'captacion' field.
   */
  public mx.baz.avro.model.liabilities.TransactionCaptacionData getCaptacion() {
    return captacion;
  }


  /**
   * Sets the value of the 'captacion' field.
   * @param value the value to set.
   */
  public void setCaptacion(mx.baz.avro.model.liabilities.TransactionCaptacionData value) {
    this.captacion = value;
  }

  /**
   * Creates a new TransactionCaptacion RecordBuilder.
   * @return A new TransactionCaptacion RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacion.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.TransactionCaptacion.Builder();
  }

  /**
   * Creates a new TransactionCaptacion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionCaptacion RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacion.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacion.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacion.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacion.Builder(other);
    }
  }

  /**
   * Creates a new TransactionCaptacion RecordBuilder by copying an existing TransactionCaptacion instance.
   * @param other The existing instance to copy.
   * @return A new TransactionCaptacion RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacion.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacion other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacion.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacion.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionCaptacion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionCaptacion>
    implements org.apache.avro.data.RecordBuilder<TransactionCaptacion> {

    private mx.baz.avro.model.liabilities.TransactionCaptacionData captacion;
    private mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder captacionBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.captacion)) {
        this.captacion = data().deepCopy(fields()[0].schema(), other.captacion);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasCaptacionBuilder()) {
        this.captacionBuilder = mx.baz.avro.model.liabilities.TransactionCaptacionData.newBuilder(other.getCaptacionBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionCaptacion instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.captacion)) {
        this.captacion = data().deepCopy(fields()[0].schema(), other.captacion);
        fieldSetFlags()[0] = true;
      }
      this.captacionBuilder = null;
    }

    /**
      * Gets the value of the 'captacion' field.
      * @return The value.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData getCaptacion() {
      return captacion;
    }


    /**
      * Sets the value of the 'captacion' field.
      * @param value The value of 'captacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacion.Builder setCaptacion(mx.baz.avro.model.liabilities.TransactionCaptacionData value) {
      validate(fields()[0], value);
      this.captacionBuilder = null;
      this.captacion = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'captacion' field has been set.
      * @return True if the 'captacion' field has been set, false otherwise.
      */
    public boolean hasCaptacion() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'captacion' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder getCaptacionBuilder() {
      if (captacionBuilder == null) {
        if (hasCaptacion()) {
          setCaptacionBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionData.newBuilder(captacion));
        } else {
          setCaptacionBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionData.newBuilder());
        }
      }
      return captacionBuilder;
    }

    /**
     * Sets the Builder instance for the 'captacion' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.TransactionCaptacion.Builder setCaptacionBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder value) {
      clearCaptacion();
      captacionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'captacion' field has an active Builder instance
     * @return True if the 'captacion' field has an active Builder instance
     */
    public boolean hasCaptacionBuilder() {
      return captacionBuilder != null;
    }

    /**
      * Clears the value of the 'captacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacion.Builder clearCaptacion() {
      captacion = null;
      captacionBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionCaptacion build() {
      try {
        TransactionCaptacion record = new TransactionCaptacion();
        if (captacionBuilder != null) {
          try {
            record.captacion = this.captacionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("captacion"));
            throw e;
          }
        } else {
          record.captacion = fieldSetFlags()[0] ? this.captacion : (mx.baz.avro.model.liabilities.TransactionCaptacionData) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionCaptacion>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionCaptacion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionCaptacion>
    READER$ = (org.apache.avro.io.DatumReader<TransactionCaptacion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.captacion.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.captacion == null) {
        this.captacion = new mx.baz.avro.model.liabilities.TransactionCaptacionData();
      }
      this.captacion.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.captacion == null) {
            this.captacion = new mx.baz.avro.model.liabilities.TransactionCaptacionData();
          }
          this.captacion.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










