/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Arreglo de datos para captacion */
@org.apache.avro.specific.AvroGenerated
public class TransactionCaptacionData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4775916627976377582L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionCaptacionData\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"doc\":\"Arreglo de datos para captacion\",\"fields\":[{\"name\":\"idCliente\",\"type\":\"string\",\"example\":\"100000001\",\"minLength\":9,\"maxLength\":9},{\"name\":\"idTipoCliente\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoEmpresa\",\"type\":\"int\",\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoRelacionEmpresa\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idSubSector\",\"type\":\"int\",\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"idNacionalidad\",\"type\":\"int\",\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoDias\",\"type\":\"int\",\"example\":0,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoMeses\",\"type\":\"int\",\"example\":36,\"minLength\":1,\"maxLength\":2},{\"name\":\"concepto\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"100000001\"},{\"name\":\"codigoProductoOriginacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"AM001\"},{\"name\":\"cuentaOriginacion\",\"type\":\"string\",\"example\":\"9674319836\",\"minLength\":10,\"maxLength\":10},{\"name\":\"folioConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"000001\",\"minLength\":2,\"maxLength\":2},{\"name\":\"fechaConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"20200216\",\"minLength\":8,\"maxLength\":8},{\"name\":\"statusConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"1\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionCaptacionData> ENCODER =
      new BinaryMessageEncoder<TransactionCaptacionData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionCaptacionData> DECODER =
      new BinaryMessageDecoder<TransactionCaptacionData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionCaptacionData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionCaptacionData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionCaptacionData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionCaptacionData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionCaptacionData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionCaptacionData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionCaptacionData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionCaptacionData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence idCliente;
   private int idTipoCliente;
   private int idTipoEmpresa;
   private int idTipoRelacionEmpresa;
   private int idSubSector;
   private int idNacionalidad;
   private int plazoDias;
   private int plazoMeses;
   private java.lang.CharSequence concepto;
   private java.lang.CharSequence codigoProductoOriginacion;
   private java.lang.CharSequence cuentaOriginacion;
   private java.lang.CharSequence folioConciliacion;
   private java.lang.CharSequence fechaConciliacion;
   private java.lang.CharSequence statusConciliacion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionCaptacionData() {}

  /**
   * All-args constructor.
   * @param idCliente The new value for idCliente
   * @param idTipoCliente The new value for idTipoCliente
   * @param idTipoEmpresa The new value for idTipoEmpresa
   * @param idTipoRelacionEmpresa The new value for idTipoRelacionEmpresa
   * @param idSubSector The new value for idSubSector
   * @param idNacionalidad The new value for idNacionalidad
   * @param plazoDias The new value for plazoDias
   * @param plazoMeses The new value for plazoMeses
   * @param concepto The new value for concepto
   * @param codigoProductoOriginacion The new value for codigoProductoOriginacion
   * @param cuentaOriginacion The new value for cuentaOriginacion
   * @param folioConciliacion The new value for folioConciliacion
   * @param fechaConciliacion The new value for fechaConciliacion
   * @param statusConciliacion The new value for statusConciliacion
   */
  public TransactionCaptacionData(java.lang.CharSequence idCliente, java.lang.Integer idTipoCliente, java.lang.Integer idTipoEmpresa, java.lang.Integer idTipoRelacionEmpresa, java.lang.Integer idSubSector, java.lang.Integer idNacionalidad, java.lang.Integer plazoDias, java.lang.Integer plazoMeses, java.lang.CharSequence concepto, java.lang.CharSequence codigoProductoOriginacion, java.lang.CharSequence cuentaOriginacion, java.lang.CharSequence folioConciliacion, java.lang.CharSequence fechaConciliacion, java.lang.CharSequence statusConciliacion) {
    this.idCliente = idCliente;
    this.idTipoCliente = idTipoCliente;
    this.idTipoEmpresa = idTipoEmpresa;
    this.idTipoRelacionEmpresa = idTipoRelacionEmpresa;
    this.idSubSector = idSubSector;
    this.idNacionalidad = idNacionalidad;
    this.plazoDias = plazoDias;
    this.plazoMeses = plazoMeses;
    this.concepto = concepto;
    this.codigoProductoOriginacion = codigoProductoOriginacion;
    this.cuentaOriginacion = cuentaOriginacion;
    this.folioConciliacion = folioConciliacion;
    this.fechaConciliacion = fechaConciliacion;
    this.statusConciliacion = statusConciliacion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idCliente;
    case 1: return idTipoCliente;
    case 2: return idTipoEmpresa;
    case 3: return idTipoRelacionEmpresa;
    case 4: return idSubSector;
    case 5: return idNacionalidad;
    case 6: return plazoDias;
    case 7: return plazoMeses;
    case 8: return concepto;
    case 9: return codigoProductoOriginacion;
    case 10: return cuentaOriginacion;
    case 11: return folioConciliacion;
    case 12: return fechaConciliacion;
    case 13: return statusConciliacion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idCliente = (java.lang.CharSequence)value$; break;
    case 1: idTipoCliente = (java.lang.Integer)value$; break;
    case 2: idTipoEmpresa = (java.lang.Integer)value$; break;
    case 3: idTipoRelacionEmpresa = (java.lang.Integer)value$; break;
    case 4: idSubSector = (java.lang.Integer)value$; break;
    case 5: idNacionalidad = (java.lang.Integer)value$; break;
    case 6: plazoDias = (java.lang.Integer)value$; break;
    case 7: plazoMeses = (java.lang.Integer)value$; break;
    case 8: concepto = (java.lang.CharSequence)value$; break;
    case 9: codigoProductoOriginacion = (java.lang.CharSequence)value$; break;
    case 10: cuentaOriginacion = (java.lang.CharSequence)value$; break;
    case 11: folioConciliacion = (java.lang.CharSequence)value$; break;
    case 12: fechaConciliacion = (java.lang.CharSequence)value$; break;
    case 13: statusConciliacion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idCliente' field.
   * @return The value of the 'idCliente' field.
   */
  public java.lang.CharSequence getIdCliente() {
    return idCliente;
  }


  /**
   * Sets the value of the 'idCliente' field.
   * @param value the value to set.
   */
  public void setIdCliente(java.lang.CharSequence value) {
    this.idCliente = value;
  }

  /**
   * Gets the value of the 'idTipoCliente' field.
   * @return The value of the 'idTipoCliente' field.
   */
  public int getIdTipoCliente() {
    return idTipoCliente;
  }


  /**
   * Sets the value of the 'idTipoCliente' field.
   * @param value the value to set.
   */
  public void setIdTipoCliente(int value) {
    this.idTipoCliente = value;
  }

  /**
   * Gets the value of the 'idTipoEmpresa' field.
   * @return The value of the 'idTipoEmpresa' field.
   */
  public int getIdTipoEmpresa() {
    return idTipoEmpresa;
  }


  /**
   * Sets the value of the 'idTipoEmpresa' field.
   * @param value the value to set.
   */
  public void setIdTipoEmpresa(int value) {
    this.idTipoEmpresa = value;
  }

  /**
   * Gets the value of the 'idTipoRelacionEmpresa' field.
   * @return The value of the 'idTipoRelacionEmpresa' field.
   */
  public int getIdTipoRelacionEmpresa() {
    return idTipoRelacionEmpresa;
  }


  /**
   * Sets the value of the 'idTipoRelacionEmpresa' field.
   * @param value the value to set.
   */
  public void setIdTipoRelacionEmpresa(int value) {
    this.idTipoRelacionEmpresa = value;
  }

  /**
   * Gets the value of the 'idSubSector' field.
   * @return The value of the 'idSubSector' field.
   */
  public int getIdSubSector() {
    return idSubSector;
  }


  /**
   * Sets the value of the 'idSubSector' field.
   * @param value the value to set.
   */
  public void setIdSubSector(int value) {
    this.idSubSector = value;
  }

  /**
   * Gets the value of the 'idNacionalidad' field.
   * @return The value of the 'idNacionalidad' field.
   */
  public int getIdNacionalidad() {
    return idNacionalidad;
  }


  /**
   * Sets the value of the 'idNacionalidad' field.
   * @param value the value to set.
   */
  public void setIdNacionalidad(int value) {
    this.idNacionalidad = value;
  }

  /**
   * Gets the value of the 'plazoDias' field.
   * @return The value of the 'plazoDias' field.
   */
  public int getPlazoDias() {
    return plazoDias;
  }


  /**
   * Sets the value of the 'plazoDias' field.
   * @param value the value to set.
   */
  public void setPlazoDias(int value) {
    this.plazoDias = value;
  }

  /**
   * Gets the value of the 'plazoMeses' field.
   * @return The value of the 'plazoMeses' field.
   */
  public int getPlazoMeses() {
    return plazoMeses;
  }


  /**
   * Sets the value of the 'plazoMeses' field.
   * @param value the value to set.
   */
  public void setPlazoMeses(int value) {
    this.plazoMeses = value;
  }

  /**
   * Gets the value of the 'concepto' field.
   * @return The value of the 'concepto' field.
   */
  public java.lang.CharSequence getConcepto() {
    return concepto;
  }


  /**
   * Sets the value of the 'concepto' field.
   * @param value the value to set.
   */
  public void setConcepto(java.lang.CharSequence value) {
    this.concepto = value;
  }

  /**
   * Gets the value of the 'codigoProductoOriginacion' field.
   * @return The value of the 'codigoProductoOriginacion' field.
   */
  public java.lang.CharSequence getCodigoProductoOriginacion() {
    return codigoProductoOriginacion;
  }


  /**
   * Sets the value of the 'codigoProductoOriginacion' field.
   * @param value the value to set.
   */
  public void setCodigoProductoOriginacion(java.lang.CharSequence value) {
    this.codigoProductoOriginacion = value;
  }

  /**
   * Gets the value of the 'cuentaOriginacion' field.
   * @return The value of the 'cuentaOriginacion' field.
   */
  public java.lang.CharSequence getCuentaOriginacion() {
    return cuentaOriginacion;
  }


  /**
   * Sets the value of the 'cuentaOriginacion' field.
   * @param value the value to set.
   */
  public void setCuentaOriginacion(java.lang.CharSequence value) {
    this.cuentaOriginacion = value;
  }

  /**
   * Gets the value of the 'folioConciliacion' field.
   * @return The value of the 'folioConciliacion' field.
   */
  public java.lang.CharSequence getFolioConciliacion() {
    return folioConciliacion;
  }


  /**
   * Sets the value of the 'folioConciliacion' field.
   * @param value the value to set.
   */
  public void setFolioConciliacion(java.lang.CharSequence value) {
    this.folioConciliacion = value;
  }

  /**
   * Gets the value of the 'fechaConciliacion' field.
   * @return The value of the 'fechaConciliacion' field.
   */
  public java.lang.CharSequence getFechaConciliacion() {
    return fechaConciliacion;
  }


  /**
   * Sets the value of the 'fechaConciliacion' field.
   * @param value the value to set.
   */
  public void setFechaConciliacion(java.lang.CharSequence value) {
    this.fechaConciliacion = value;
  }

  /**
   * Gets the value of the 'statusConciliacion' field.
   * @return The value of the 'statusConciliacion' field.
   */
  public java.lang.CharSequence getStatusConciliacion() {
    return statusConciliacion;
  }


  /**
   * Sets the value of the 'statusConciliacion' field.
   * @param value the value to set.
   */
  public void setStatusConciliacion(java.lang.CharSequence value) {
    this.statusConciliacion = value;
  }

  /**
   * Creates a new TransactionCaptacionData RecordBuilder.
   * @return A new TransactionCaptacionData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder();
  }

  /**
   * Creates a new TransactionCaptacionData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionCaptacionData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder(other);
    }
  }

  /**
   * Creates a new TransactionCaptacionData RecordBuilder by copying an existing TransactionCaptacionData instance.
   * @param other The existing instance to copy.
   * @return A new TransactionCaptacionData RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionData other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionCaptacionData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionCaptacionData>
    implements org.apache.avro.data.RecordBuilder<TransactionCaptacionData> {

    private java.lang.CharSequence idCliente;
    private int idTipoCliente;
    private int idTipoEmpresa;
    private int idTipoRelacionEmpresa;
    private int idSubSector;
    private int idNacionalidad;
    private int plazoDias;
    private int plazoMeses;
    private java.lang.CharSequence concepto;
    private java.lang.CharSequence codigoProductoOriginacion;
    private java.lang.CharSequence cuentaOriginacion;
    private java.lang.CharSequence folioConciliacion;
    private java.lang.CharSequence fechaConciliacion;
    private java.lang.CharSequence statusConciliacion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idCliente)) {
        this.idCliente = data().deepCopy(fields()[0].schema(), other.idCliente);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.idTipoCliente)) {
        this.idTipoCliente = data().deepCopy(fields()[1].schema(), other.idTipoCliente);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.idTipoEmpresa)) {
        this.idTipoEmpresa = data().deepCopy(fields()[2].schema(), other.idTipoEmpresa);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.idTipoRelacionEmpresa)) {
        this.idTipoRelacionEmpresa = data().deepCopy(fields()[3].schema(), other.idTipoRelacionEmpresa);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.idSubSector)) {
        this.idSubSector = data().deepCopy(fields()[4].schema(), other.idSubSector);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.idNacionalidad)) {
        this.idNacionalidad = data().deepCopy(fields()[5].schema(), other.idNacionalidad);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.plazoDias)) {
        this.plazoDias = data().deepCopy(fields()[6].schema(), other.plazoDias);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.plazoMeses)) {
        this.plazoMeses = data().deepCopy(fields()[7].schema(), other.plazoMeses);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.concepto)) {
        this.concepto = data().deepCopy(fields()[8].schema(), other.concepto);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.codigoProductoOriginacion)) {
        this.codigoProductoOriginacion = data().deepCopy(fields()[9].schema(), other.codigoProductoOriginacion);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.cuentaOriginacion)) {
        this.cuentaOriginacion = data().deepCopy(fields()[10].schema(), other.cuentaOriginacion);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.folioConciliacion)) {
        this.folioConciliacion = data().deepCopy(fields()[11].schema(), other.folioConciliacion);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.fechaConciliacion)) {
        this.fechaConciliacion = data().deepCopy(fields()[12].schema(), other.fechaConciliacion);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.statusConciliacion)) {
        this.statusConciliacion = data().deepCopy(fields()[13].schema(), other.statusConciliacion);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionCaptacionData instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idCliente)) {
        this.idCliente = data().deepCopy(fields()[0].schema(), other.idCliente);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idTipoCliente)) {
        this.idTipoCliente = data().deepCopy(fields()[1].schema(), other.idTipoCliente);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.idTipoEmpresa)) {
        this.idTipoEmpresa = data().deepCopy(fields()[2].schema(), other.idTipoEmpresa);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.idTipoRelacionEmpresa)) {
        this.idTipoRelacionEmpresa = data().deepCopy(fields()[3].schema(), other.idTipoRelacionEmpresa);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.idSubSector)) {
        this.idSubSector = data().deepCopy(fields()[4].schema(), other.idSubSector);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.idNacionalidad)) {
        this.idNacionalidad = data().deepCopy(fields()[5].schema(), other.idNacionalidad);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.plazoDias)) {
        this.plazoDias = data().deepCopy(fields()[6].schema(), other.plazoDias);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.plazoMeses)) {
        this.plazoMeses = data().deepCopy(fields()[7].schema(), other.plazoMeses);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.concepto)) {
        this.concepto = data().deepCopy(fields()[8].schema(), other.concepto);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.codigoProductoOriginacion)) {
        this.codigoProductoOriginacion = data().deepCopy(fields()[9].schema(), other.codigoProductoOriginacion);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.cuentaOriginacion)) {
        this.cuentaOriginacion = data().deepCopy(fields()[10].schema(), other.cuentaOriginacion);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.folioConciliacion)) {
        this.folioConciliacion = data().deepCopy(fields()[11].schema(), other.folioConciliacion);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.fechaConciliacion)) {
        this.fechaConciliacion = data().deepCopy(fields()[12].schema(), other.fechaConciliacion);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.statusConciliacion)) {
        this.statusConciliacion = data().deepCopy(fields()[13].schema(), other.statusConciliacion);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'idCliente' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdCliente() {
      return idCliente;
    }


    /**
      * Sets the value of the 'idCliente' field.
      * @param value The value of 'idCliente'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdCliente(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.idCliente = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idCliente' field has been set.
      * @return True if the 'idCliente' field has been set, false otherwise.
      */
    public boolean hasIdCliente() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idCliente' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdCliente() {
      idCliente = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idTipoCliente' field.
      * @return The value.
      */
    public int getIdTipoCliente() {
      return idTipoCliente;
    }


    /**
      * Sets the value of the 'idTipoCliente' field.
      * @param value The value of 'idTipoCliente'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdTipoCliente(int value) {
      validate(fields()[1], value);
      this.idTipoCliente = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idTipoCliente' field has been set.
      * @return True if the 'idTipoCliente' field has been set, false otherwise.
      */
    public boolean hasIdTipoCliente() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idTipoCliente' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdTipoCliente() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'idTipoEmpresa' field.
      * @return The value.
      */
    public int getIdTipoEmpresa() {
      return idTipoEmpresa;
    }


    /**
      * Sets the value of the 'idTipoEmpresa' field.
      * @param value The value of 'idTipoEmpresa'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdTipoEmpresa(int value) {
      validate(fields()[2], value);
      this.idTipoEmpresa = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'idTipoEmpresa' field has been set.
      * @return True if the 'idTipoEmpresa' field has been set, false otherwise.
      */
    public boolean hasIdTipoEmpresa() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'idTipoEmpresa' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdTipoEmpresa() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'idTipoRelacionEmpresa' field.
      * @return The value.
      */
    public int getIdTipoRelacionEmpresa() {
      return idTipoRelacionEmpresa;
    }


    /**
      * Sets the value of the 'idTipoRelacionEmpresa' field.
      * @param value The value of 'idTipoRelacionEmpresa'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdTipoRelacionEmpresa(int value) {
      validate(fields()[3], value);
      this.idTipoRelacionEmpresa = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'idTipoRelacionEmpresa' field has been set.
      * @return True if the 'idTipoRelacionEmpresa' field has been set, false otherwise.
      */
    public boolean hasIdTipoRelacionEmpresa() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'idTipoRelacionEmpresa' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdTipoRelacionEmpresa() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'idSubSector' field.
      * @return The value.
      */
    public int getIdSubSector() {
      return idSubSector;
    }


    /**
      * Sets the value of the 'idSubSector' field.
      * @param value The value of 'idSubSector'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdSubSector(int value) {
      validate(fields()[4], value);
      this.idSubSector = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'idSubSector' field has been set.
      * @return True if the 'idSubSector' field has been set, false otherwise.
      */
    public boolean hasIdSubSector() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'idSubSector' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdSubSector() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'idNacionalidad' field.
      * @return The value.
      */
    public int getIdNacionalidad() {
      return idNacionalidad;
    }


    /**
      * Sets the value of the 'idNacionalidad' field.
      * @param value The value of 'idNacionalidad'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setIdNacionalidad(int value) {
      validate(fields()[5], value);
      this.idNacionalidad = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'idNacionalidad' field has been set.
      * @return True if the 'idNacionalidad' field has been set, false otherwise.
      */
    public boolean hasIdNacionalidad() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'idNacionalidad' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearIdNacionalidad() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'plazoDias' field.
      * @return The value.
      */
    public int getPlazoDias() {
      return plazoDias;
    }


    /**
      * Sets the value of the 'plazoDias' field.
      * @param value The value of 'plazoDias'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setPlazoDias(int value) {
      validate(fields()[6], value);
      this.plazoDias = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'plazoDias' field has been set.
      * @return True if the 'plazoDias' field has been set, false otherwise.
      */
    public boolean hasPlazoDias() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'plazoDias' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearPlazoDias() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'plazoMeses' field.
      * @return The value.
      */
    public int getPlazoMeses() {
      return plazoMeses;
    }


    /**
      * Sets the value of the 'plazoMeses' field.
      * @param value The value of 'plazoMeses'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setPlazoMeses(int value) {
      validate(fields()[7], value);
      this.plazoMeses = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'plazoMeses' field has been set.
      * @return True if the 'plazoMeses' field has been set, false otherwise.
      */
    public boolean hasPlazoMeses() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'plazoMeses' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearPlazoMeses() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'concepto' field.
      * @return The value.
      */
    public java.lang.CharSequence getConcepto() {
      return concepto;
    }


    /**
      * Sets the value of the 'concepto' field.
      * @param value The value of 'concepto'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setConcepto(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.concepto = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'concepto' field has been set.
      * @return True if the 'concepto' field has been set, false otherwise.
      */
    public boolean hasConcepto() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'concepto' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearConcepto() {
      concepto = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigoProductoOriginacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoProductoOriginacion() {
      return codigoProductoOriginacion;
    }


    /**
      * Sets the value of the 'codigoProductoOriginacion' field.
      * @param value The value of 'codigoProductoOriginacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setCodigoProductoOriginacion(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.codigoProductoOriginacion = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'codigoProductoOriginacion' field has been set.
      * @return True if the 'codigoProductoOriginacion' field has been set, false otherwise.
      */
    public boolean hasCodigoProductoOriginacion() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'codigoProductoOriginacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearCodigoProductoOriginacion() {
      codigoProductoOriginacion = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'cuentaOriginacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getCuentaOriginacion() {
      return cuentaOriginacion;
    }


    /**
      * Sets the value of the 'cuentaOriginacion' field.
      * @param value The value of 'cuentaOriginacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setCuentaOriginacion(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.cuentaOriginacion = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'cuentaOriginacion' field has been set.
      * @return True if the 'cuentaOriginacion' field has been set, false otherwise.
      */
    public boolean hasCuentaOriginacion() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'cuentaOriginacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearCuentaOriginacion() {
      cuentaOriginacion = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'folioConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFolioConciliacion() {
      return folioConciliacion;
    }


    /**
      * Sets the value of the 'folioConciliacion' field.
      * @param value The value of 'folioConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setFolioConciliacion(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.folioConciliacion = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'folioConciliacion' field has been set.
      * @return True if the 'folioConciliacion' field has been set, false otherwise.
      */
    public boolean hasFolioConciliacion() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'folioConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearFolioConciliacion() {
      folioConciliacion = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaConciliacion() {
      return fechaConciliacion;
    }


    /**
      * Sets the value of the 'fechaConciliacion' field.
      * @param value The value of 'fechaConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setFechaConciliacion(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.fechaConciliacion = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaConciliacion' field has been set.
      * @return True if the 'fechaConciliacion' field has been set, false otherwise.
      */
    public boolean hasFechaConciliacion() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'fechaConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearFechaConciliacion() {
      fechaConciliacion = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'statusConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusConciliacion() {
      return statusConciliacion;
    }


    /**
      * Sets the value of the 'statusConciliacion' field.
      * @param value The value of 'statusConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder setStatusConciliacion(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.statusConciliacion = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'statusConciliacion' field has been set.
      * @return True if the 'statusConciliacion' field has been set, false otherwise.
      */
    public boolean hasStatusConciliacion() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'statusConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionData.Builder clearStatusConciliacion() {
      statusConciliacion = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionCaptacionData build() {
      try {
        TransactionCaptacionData record = new TransactionCaptacionData();
        record.idCliente = fieldSetFlags()[0] ? this.idCliente : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.idTipoCliente = fieldSetFlags()[1] ? this.idTipoCliente : (java.lang.Integer) defaultValue(fields()[1]);
        record.idTipoEmpresa = fieldSetFlags()[2] ? this.idTipoEmpresa : (java.lang.Integer) defaultValue(fields()[2]);
        record.idTipoRelacionEmpresa = fieldSetFlags()[3] ? this.idTipoRelacionEmpresa : (java.lang.Integer) defaultValue(fields()[3]);
        record.idSubSector = fieldSetFlags()[4] ? this.idSubSector : (java.lang.Integer) defaultValue(fields()[4]);
        record.idNacionalidad = fieldSetFlags()[5] ? this.idNacionalidad : (java.lang.Integer) defaultValue(fields()[5]);
        record.plazoDias = fieldSetFlags()[6] ? this.plazoDias : (java.lang.Integer) defaultValue(fields()[6]);
        record.plazoMeses = fieldSetFlags()[7] ? this.plazoMeses : (java.lang.Integer) defaultValue(fields()[7]);
        record.concepto = fieldSetFlags()[8] ? this.concepto : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.codigoProductoOriginacion = fieldSetFlags()[9] ? this.codigoProductoOriginacion : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.cuentaOriginacion = fieldSetFlags()[10] ? this.cuentaOriginacion : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.folioConciliacion = fieldSetFlags()[11] ? this.folioConciliacion : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.fechaConciliacion = fieldSetFlags()[12] ? this.fechaConciliacion : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.statusConciliacion = fieldSetFlags()[13] ? this.statusConciliacion : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionCaptacionData>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionCaptacionData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionCaptacionData>
    READER$ = (org.apache.avro.io.DatumReader<TransactionCaptacionData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.idCliente);

    out.writeInt(this.idTipoCliente);

    out.writeInt(this.idTipoEmpresa);

    out.writeInt(this.idTipoRelacionEmpresa);

    out.writeInt(this.idSubSector);

    out.writeInt(this.idNacionalidad);

    out.writeInt(this.plazoDias);

    out.writeInt(this.plazoMeses);

    if (this.concepto == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.concepto);
    }

    if (this.codigoProductoOriginacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.codigoProductoOriginacion);
    }

    out.writeString(this.cuentaOriginacion);

    if (this.folioConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.folioConciliacion);
    }

    if (this.fechaConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fechaConciliacion);
    }

    if (this.statusConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.statusConciliacion);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idCliente = in.readString(this.idCliente instanceof Utf8 ? (Utf8)this.idCliente : null);

      this.idTipoCliente = in.readInt();

      this.idTipoEmpresa = in.readInt();

      this.idTipoRelacionEmpresa = in.readInt();

      this.idSubSector = in.readInt();

      this.idNacionalidad = in.readInt();

      this.plazoDias = in.readInt();

      this.plazoMeses = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.concepto = null;
      } else {
        this.concepto = in.readString(this.concepto instanceof Utf8 ? (Utf8)this.concepto : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.codigoProductoOriginacion = null;
      } else {
        this.codigoProductoOriginacion = in.readString(this.codigoProductoOriginacion instanceof Utf8 ? (Utf8)this.codigoProductoOriginacion : null);
      }

      this.cuentaOriginacion = in.readString(this.cuentaOriginacion instanceof Utf8 ? (Utf8)this.cuentaOriginacion : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.folioConciliacion = null;
      } else {
        this.folioConciliacion = in.readString(this.folioConciliacion instanceof Utf8 ? (Utf8)this.folioConciliacion : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fechaConciliacion = null;
      } else {
        this.fechaConciliacion = in.readString(this.fechaConciliacion instanceof Utf8 ? (Utf8)this.fechaConciliacion : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.statusConciliacion = null;
      } else {
        this.statusConciliacion = in.readString(this.statusConciliacion instanceof Utf8 ? (Utf8)this.statusConciliacion : null);
      }

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idCliente = in.readString(this.idCliente instanceof Utf8 ? (Utf8)this.idCliente : null);
          break;

        case 1:
          this.idTipoCliente = in.readInt();
          break;

        case 2:
          this.idTipoEmpresa = in.readInt();
          break;

        case 3:
          this.idTipoRelacionEmpresa = in.readInt();
          break;

        case 4:
          this.idSubSector = in.readInt();
          break;

        case 5:
          this.idNacionalidad = in.readInt();
          break;

        case 6:
          this.plazoDias = in.readInt();
          break;

        case 7:
          this.plazoMeses = in.readInt();
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.concepto = null;
          } else {
            this.concepto = in.readString(this.concepto instanceof Utf8 ? (Utf8)this.concepto : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.codigoProductoOriginacion = null;
          } else {
            this.codigoProductoOriginacion = in.readString(this.codigoProductoOriginacion instanceof Utf8 ? (Utf8)this.codigoProductoOriginacion : null);
          }
          break;

        case 10:
          this.cuentaOriginacion = in.readString(this.cuentaOriginacion instanceof Utf8 ? (Utf8)this.cuentaOriginacion : null);
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.folioConciliacion = null;
          } else {
            this.folioConciliacion = in.readString(this.folioConciliacion instanceof Utf8 ? (Utf8)this.folioConciliacion : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fechaConciliacion = null;
          } else {
            this.fechaConciliacion = in.readString(this.fechaConciliacion instanceof Utf8 ? (Utf8)this.fechaConciliacion : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.statusConciliacion = null;
          } else {
            this.statusConciliacion = in.readString(this.statusConciliacion instanceof Utf8 ? (Utf8)this.statusConciliacion : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










