/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionCaptacionConsolidated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3990090605304045092L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionCaptacionConsolidated\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"fields\":[{\"name\":\"captacionAgrupado\",\"type\":{\"type\":\"record\",\"name\":\"TransactionCaptacionDataConsolidated\",\"doc\":\"Arreglo de datos para captacion\",\"fields\":[{\"name\":\"idTipoCliente\",\"type\":[\"null\",\"int\"],\"default\":null,\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoEmpresa\",\"type\":[\"null\",\"int\"],\"default\":null,\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoDias\",\"type\":\"int\",\"example\":\"0\",\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoMeses\",\"type\":\"int\",\"example\":\"36\",\"minLength\":1,\"maxLength\":2},{\"name\":\"codigoProductoOriginacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"AM001\"},{\"name\":\"folioConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"000001\",\"minLength\":2,\"maxLength\":2},{\"name\":\"fechaConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"20200216\",\"minLength\":8,\"maxLength\":8},{\"name\":\"statusConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"1\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionCaptacionConsolidated> ENCODER =
      new BinaryMessageEncoder<TransactionCaptacionConsolidated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionCaptacionConsolidated> DECODER =
      new BinaryMessageDecoder<TransactionCaptacionConsolidated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionCaptacionConsolidated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionCaptacionConsolidated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionCaptacionConsolidated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionCaptacionConsolidated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionCaptacionConsolidated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionCaptacionConsolidated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionCaptacionConsolidated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionCaptacionConsolidated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated captacionAgrupado;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionCaptacionConsolidated() {}

  /**
   * All-args constructor.
   * @param captacionAgrupado The new value for captacionAgrupado
   */
  public TransactionCaptacionConsolidated(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated captacionAgrupado) {
    this.captacionAgrupado = captacionAgrupado;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return captacionAgrupado;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: captacionAgrupado = (mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'captacionAgrupado' field.
   * @return The value of the 'captacionAgrupado' field.
   */
  public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated getCaptacionAgrupado() {
    return captacionAgrupado;
  }


  /**
   * Sets the value of the 'captacionAgrupado' field.
   * @param value the value to set.
   */
  public void setCaptacionAgrupado(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated value) {
    this.captacionAgrupado = value;
  }

  /**
   * Creates a new TransactionCaptacionConsolidated RecordBuilder.
   * @return A new TransactionCaptacionConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder();
  }

  /**
   * Creates a new TransactionCaptacionConsolidated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionCaptacionConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder(other);
    }
  }

  /**
   * Creates a new TransactionCaptacionConsolidated RecordBuilder by copying an existing TransactionCaptacionConsolidated instance.
   * @param other The existing instance to copy.
   * @return A new TransactionCaptacionConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionCaptacionConsolidated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionCaptacionConsolidated>
    implements org.apache.avro.data.RecordBuilder<TransactionCaptacionConsolidated> {

    private mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated captacionAgrupado;
    private mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder captacionAgrupadoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.captacionAgrupado)) {
        this.captacionAgrupado = data().deepCopy(fields()[0].schema(), other.captacionAgrupado);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasCaptacionAgrupadoBuilder()) {
        this.captacionAgrupadoBuilder = mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.newBuilder(other.getCaptacionAgrupadoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionCaptacionConsolidated instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.captacionAgrupado)) {
        this.captacionAgrupado = data().deepCopy(fields()[0].schema(), other.captacionAgrupado);
        fieldSetFlags()[0] = true;
      }
      this.captacionAgrupadoBuilder = null;
    }

    /**
      * Gets the value of the 'captacionAgrupado' field.
      * @return The value.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated getCaptacionAgrupado() {
      return captacionAgrupado;
    }


    /**
      * Sets the value of the 'captacionAgrupado' field.
      * @param value The value of 'captacionAgrupado'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder setCaptacionAgrupado(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated value) {
      validate(fields()[0], value);
      this.captacionAgrupadoBuilder = null;
      this.captacionAgrupado = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'captacionAgrupado' field has been set.
      * @return True if the 'captacionAgrupado' field has been set, false otherwise.
      */
    public boolean hasCaptacionAgrupado() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'captacionAgrupado' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder getCaptacionAgrupadoBuilder() {
      if (captacionAgrupadoBuilder == null) {
        if (hasCaptacionAgrupado()) {
          setCaptacionAgrupadoBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.newBuilder(captacionAgrupado));
        } else {
          setCaptacionAgrupadoBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.newBuilder());
        }
      }
      return captacionAgrupadoBuilder;
    }

    /**
     * Sets the Builder instance for the 'captacionAgrupado' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder setCaptacionAgrupadoBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder value) {
      clearCaptacionAgrupado();
      captacionAgrupadoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'captacionAgrupado' field has an active Builder instance
     * @return True if the 'captacionAgrupado' field has an active Builder instance
     */
    public boolean hasCaptacionAgrupadoBuilder() {
      return captacionAgrupadoBuilder != null;
    }

    /**
      * Clears the value of the 'captacionAgrupado' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionConsolidated.Builder clearCaptacionAgrupado() {
      captacionAgrupado = null;
      captacionAgrupadoBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionCaptacionConsolidated build() {
      try {
        TransactionCaptacionConsolidated record = new TransactionCaptacionConsolidated();
        if (captacionAgrupadoBuilder != null) {
          try {
            record.captacionAgrupado = this.captacionAgrupadoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("captacionAgrupado"));
            throw e;
          }
        } else {
          record.captacionAgrupado = fieldSetFlags()[0] ? this.captacionAgrupado : (mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionCaptacionConsolidated>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionCaptacionConsolidated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionCaptacionConsolidated>
    READER$ = (org.apache.avro.io.DatumReader<TransactionCaptacionConsolidated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.captacionAgrupado.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.captacionAgrupado == null) {
        this.captacionAgrupado = new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated();
      }
      this.captacionAgrupado.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.captacionAgrupado == null) {
            this.captacionAgrupado = new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated();
          }
          this.captacionAgrupado.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










