/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mx.baz.avro.model.liabilities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Arreglo de datos para captacion */
@org.apache.avro.specific.AvroGenerated
public class TransactionCaptacionDataConsolidated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8386211293127934211L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionCaptacionDataConsolidated\",\"namespace\":\"mx.baz.avro.model.liabilities\",\"doc\":\"Arreglo de datos para captacion\",\"fields\":[{\"name\":\"idTipoCliente\",\"type\":[\"null\",\"int\"],\"default\":null,\"example\":1,\"minLength\":1,\"maxLength\":2},{\"name\":\"idTipoEmpresa\",\"type\":[\"null\",\"int\"],\"default\":null,\"example\":2,\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoDias\",\"type\":\"int\",\"example\":\"0\",\"minLength\":1,\"maxLength\":2},{\"name\":\"plazoMeses\",\"type\":\"int\",\"example\":\"36\",\"minLength\":1,\"maxLength\":2},{\"name\":\"codigoProductoOriginacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"AM001\"},{\"name\":\"folioConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"000001\",\"minLength\":2,\"maxLength\":2},{\"name\":\"fechaConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"20200216\",\"minLength\":8,\"maxLength\":8},{\"name\":\"statusConciliacion\",\"type\":[\"null\",\"string\"],\"default\":null,\"example\":\"1\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionCaptacionDataConsolidated> ENCODER =
      new BinaryMessageEncoder<TransactionCaptacionDataConsolidated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionCaptacionDataConsolidated> DECODER =
      new BinaryMessageDecoder<TransactionCaptacionDataConsolidated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionCaptacionDataConsolidated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionCaptacionDataConsolidated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionCaptacionDataConsolidated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionCaptacionDataConsolidated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionCaptacionDataConsolidated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionCaptacionDataConsolidated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionCaptacionDataConsolidated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionCaptacionDataConsolidated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Integer idTipoCliente;
   private java.lang.Integer idTipoEmpresa;
   private int plazoDias;
   private int plazoMeses;
   private java.lang.CharSequence codigoProductoOriginacion;
   private java.lang.CharSequence folioConciliacion;
   private java.lang.CharSequence fechaConciliacion;
   private java.lang.CharSequence statusConciliacion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionCaptacionDataConsolidated() {}

  /**
   * All-args constructor.
   * @param idTipoCliente The new value for idTipoCliente
   * @param idTipoEmpresa The new value for idTipoEmpresa
   * @param plazoDias The new value for plazoDias
   * @param plazoMeses The new value for plazoMeses
   * @param codigoProductoOriginacion The new value for codigoProductoOriginacion
   * @param folioConciliacion The new value for folioConciliacion
   * @param fechaConciliacion The new value for fechaConciliacion
   * @param statusConciliacion The new value for statusConciliacion
   */
  public TransactionCaptacionDataConsolidated(java.lang.Integer idTipoCliente, java.lang.Integer idTipoEmpresa, java.lang.Integer plazoDias, java.lang.Integer plazoMeses, java.lang.CharSequence codigoProductoOriginacion, java.lang.CharSequence folioConciliacion, java.lang.CharSequence fechaConciliacion, java.lang.CharSequence statusConciliacion) {
    this.idTipoCliente = idTipoCliente;
    this.idTipoEmpresa = idTipoEmpresa;
    this.plazoDias = plazoDias;
    this.plazoMeses = plazoMeses;
    this.codigoProductoOriginacion = codigoProductoOriginacion;
    this.folioConciliacion = folioConciliacion;
    this.fechaConciliacion = fechaConciliacion;
    this.statusConciliacion = statusConciliacion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idTipoCliente;
    case 1: return idTipoEmpresa;
    case 2: return plazoDias;
    case 3: return plazoMeses;
    case 4: return codigoProductoOriginacion;
    case 5: return folioConciliacion;
    case 6: return fechaConciliacion;
    case 7: return statusConciliacion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idTipoCliente = (java.lang.Integer)value$; break;
    case 1: idTipoEmpresa = (java.lang.Integer)value$; break;
    case 2: plazoDias = (java.lang.Integer)value$; break;
    case 3: plazoMeses = (java.lang.Integer)value$; break;
    case 4: codigoProductoOriginacion = (java.lang.CharSequence)value$; break;
    case 5: folioConciliacion = (java.lang.CharSequence)value$; break;
    case 6: fechaConciliacion = (java.lang.CharSequence)value$; break;
    case 7: statusConciliacion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idTipoCliente' field.
   * @return The value of the 'idTipoCliente' field.
   */
  public java.lang.Integer getIdTipoCliente() {
    return idTipoCliente;
  }


  /**
   * Sets the value of the 'idTipoCliente' field.
   * @param value the value to set.
   */
  public void setIdTipoCliente(java.lang.Integer value) {
    this.idTipoCliente = value;
  }

  /**
   * Gets the value of the 'idTipoEmpresa' field.
   * @return The value of the 'idTipoEmpresa' field.
   */
  public java.lang.Integer getIdTipoEmpresa() {
    return idTipoEmpresa;
  }


  /**
   * Sets the value of the 'idTipoEmpresa' field.
   * @param value the value to set.
   */
  public void setIdTipoEmpresa(java.lang.Integer value) {
    this.idTipoEmpresa = value;
  }

  /**
   * Gets the value of the 'plazoDias' field.
   * @return The value of the 'plazoDias' field.
   */
  public int getPlazoDias() {
    return plazoDias;
  }


  /**
   * Sets the value of the 'plazoDias' field.
   * @param value the value to set.
   */
  public void setPlazoDias(int value) {
    this.plazoDias = value;
  }

  /**
   * Gets the value of the 'plazoMeses' field.
   * @return The value of the 'plazoMeses' field.
   */
  public int getPlazoMeses() {
    return plazoMeses;
  }


  /**
   * Sets the value of the 'plazoMeses' field.
   * @param value the value to set.
   */
  public void setPlazoMeses(int value) {
    this.plazoMeses = value;
  }

  /**
   * Gets the value of the 'codigoProductoOriginacion' field.
   * @return The value of the 'codigoProductoOriginacion' field.
   */
  public java.lang.CharSequence getCodigoProductoOriginacion() {
    return codigoProductoOriginacion;
  }


  /**
   * Sets the value of the 'codigoProductoOriginacion' field.
   * @param value the value to set.
   */
  public void setCodigoProductoOriginacion(java.lang.CharSequence value) {
    this.codigoProductoOriginacion = value;
  }

  /**
   * Gets the value of the 'folioConciliacion' field.
   * @return The value of the 'folioConciliacion' field.
   */
  public java.lang.CharSequence getFolioConciliacion() {
    return folioConciliacion;
  }


  /**
   * Sets the value of the 'folioConciliacion' field.
   * @param value the value to set.
   */
  public void setFolioConciliacion(java.lang.CharSequence value) {
    this.folioConciliacion = value;
  }

  /**
   * Gets the value of the 'fechaConciliacion' field.
   * @return The value of the 'fechaConciliacion' field.
   */
  public java.lang.CharSequence getFechaConciliacion() {
    return fechaConciliacion;
  }


  /**
   * Sets the value of the 'fechaConciliacion' field.
   * @param value the value to set.
   */
  public void setFechaConciliacion(java.lang.CharSequence value) {
    this.fechaConciliacion = value;
  }

  /**
   * Gets the value of the 'statusConciliacion' field.
   * @return The value of the 'statusConciliacion' field.
   */
  public java.lang.CharSequence getStatusConciliacion() {
    return statusConciliacion;
  }


  /**
   * Sets the value of the 'statusConciliacion' field.
   * @param value the value to set.
   */
  public void setStatusConciliacion(java.lang.CharSequence value) {
    this.statusConciliacion = value;
  }

  /**
   * Creates a new TransactionCaptacionDataConsolidated RecordBuilder.
   * @return A new TransactionCaptacionDataConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder newBuilder() {
    return new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder();
  }

  /**
   * Creates a new TransactionCaptacionDataConsolidated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionCaptacionDataConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder(other);
    }
  }

  /**
   * Creates a new TransactionCaptacionDataConsolidated RecordBuilder by copying an existing TransactionCaptacionDataConsolidated instance.
   * @param other The existing instance to copy.
   * @return A new TransactionCaptacionDataConsolidated RecordBuilder
   */
  public static mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder newBuilder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated other) {
    if (other == null) {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder();
    } else {
      return new mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionCaptacionDataConsolidated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionCaptacionDataConsolidated>
    implements org.apache.avro.data.RecordBuilder<TransactionCaptacionDataConsolidated> {

    private java.lang.Integer idTipoCliente;
    private java.lang.Integer idTipoEmpresa;
    private int plazoDias;
    private int plazoMeses;
    private java.lang.CharSequence codigoProductoOriginacion;
    private java.lang.CharSequence folioConciliacion;
    private java.lang.CharSequence fechaConciliacion;
    private java.lang.CharSequence statusConciliacion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idTipoCliente)) {
        this.idTipoCliente = data().deepCopy(fields()[0].schema(), other.idTipoCliente);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.idTipoEmpresa)) {
        this.idTipoEmpresa = data().deepCopy(fields()[1].schema(), other.idTipoEmpresa);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.plazoDias)) {
        this.plazoDias = data().deepCopy(fields()[2].schema(), other.plazoDias);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.plazoMeses)) {
        this.plazoMeses = data().deepCopy(fields()[3].schema(), other.plazoMeses);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.codigoProductoOriginacion)) {
        this.codigoProductoOriginacion = data().deepCopy(fields()[4].schema(), other.codigoProductoOriginacion);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.folioConciliacion)) {
        this.folioConciliacion = data().deepCopy(fields()[5].schema(), other.folioConciliacion);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.fechaConciliacion)) {
        this.fechaConciliacion = data().deepCopy(fields()[6].schema(), other.fechaConciliacion);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.statusConciliacion)) {
        this.statusConciliacion = data().deepCopy(fields()[7].schema(), other.statusConciliacion);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionCaptacionDataConsolidated instance
     * @param other The existing instance to copy.
     */
    private Builder(mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idTipoCliente)) {
        this.idTipoCliente = data().deepCopy(fields()[0].schema(), other.idTipoCliente);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idTipoEmpresa)) {
        this.idTipoEmpresa = data().deepCopy(fields()[1].schema(), other.idTipoEmpresa);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.plazoDias)) {
        this.plazoDias = data().deepCopy(fields()[2].schema(), other.plazoDias);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.plazoMeses)) {
        this.plazoMeses = data().deepCopy(fields()[3].schema(), other.plazoMeses);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.codigoProductoOriginacion)) {
        this.codigoProductoOriginacion = data().deepCopy(fields()[4].schema(), other.codigoProductoOriginacion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.folioConciliacion)) {
        this.folioConciliacion = data().deepCopy(fields()[5].schema(), other.folioConciliacion);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.fechaConciliacion)) {
        this.fechaConciliacion = data().deepCopy(fields()[6].schema(), other.fechaConciliacion);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.statusConciliacion)) {
        this.statusConciliacion = data().deepCopy(fields()[7].schema(), other.statusConciliacion);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'idTipoCliente' field.
      * @return The value.
      */
    public java.lang.Integer getIdTipoCliente() {
      return idTipoCliente;
    }


    /**
      * Sets the value of the 'idTipoCliente' field.
      * @param value The value of 'idTipoCliente'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setIdTipoCliente(java.lang.Integer value) {
      validate(fields()[0], value);
      this.idTipoCliente = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idTipoCliente' field has been set.
      * @return True if the 'idTipoCliente' field has been set, false otherwise.
      */
    public boolean hasIdTipoCliente() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idTipoCliente' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearIdTipoCliente() {
      idTipoCliente = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idTipoEmpresa' field.
      * @return The value.
      */
    public java.lang.Integer getIdTipoEmpresa() {
      return idTipoEmpresa;
    }


    /**
      * Sets the value of the 'idTipoEmpresa' field.
      * @param value The value of 'idTipoEmpresa'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setIdTipoEmpresa(java.lang.Integer value) {
      validate(fields()[1], value);
      this.idTipoEmpresa = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idTipoEmpresa' field has been set.
      * @return True if the 'idTipoEmpresa' field has been set, false otherwise.
      */
    public boolean hasIdTipoEmpresa() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idTipoEmpresa' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearIdTipoEmpresa() {
      idTipoEmpresa = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'plazoDias' field.
      * @return The value.
      */
    public int getPlazoDias() {
      return plazoDias;
    }


    /**
      * Sets the value of the 'plazoDias' field.
      * @param value The value of 'plazoDias'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setPlazoDias(int value) {
      validate(fields()[2], value);
      this.plazoDias = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'plazoDias' field has been set.
      * @return True if the 'plazoDias' field has been set, false otherwise.
      */
    public boolean hasPlazoDias() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'plazoDias' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearPlazoDias() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'plazoMeses' field.
      * @return The value.
      */
    public int getPlazoMeses() {
      return plazoMeses;
    }


    /**
      * Sets the value of the 'plazoMeses' field.
      * @param value The value of 'plazoMeses'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setPlazoMeses(int value) {
      validate(fields()[3], value);
      this.plazoMeses = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'plazoMeses' field has been set.
      * @return True if the 'plazoMeses' field has been set, false otherwise.
      */
    public boolean hasPlazoMeses() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'plazoMeses' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearPlazoMeses() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigoProductoOriginacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoProductoOriginacion() {
      return codigoProductoOriginacion;
    }


    /**
      * Sets the value of the 'codigoProductoOriginacion' field.
      * @param value The value of 'codigoProductoOriginacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setCodigoProductoOriginacion(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.codigoProductoOriginacion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'codigoProductoOriginacion' field has been set.
      * @return True if the 'codigoProductoOriginacion' field has been set, false otherwise.
      */
    public boolean hasCodigoProductoOriginacion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'codigoProductoOriginacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearCodigoProductoOriginacion() {
      codigoProductoOriginacion = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'folioConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFolioConciliacion() {
      return folioConciliacion;
    }


    /**
      * Sets the value of the 'folioConciliacion' field.
      * @param value The value of 'folioConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setFolioConciliacion(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.folioConciliacion = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'folioConciliacion' field has been set.
      * @return True if the 'folioConciliacion' field has been set, false otherwise.
      */
    public boolean hasFolioConciliacion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'folioConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearFolioConciliacion() {
      folioConciliacion = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaConciliacion() {
      return fechaConciliacion;
    }


    /**
      * Sets the value of the 'fechaConciliacion' field.
      * @param value The value of 'fechaConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setFechaConciliacion(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.fechaConciliacion = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaConciliacion' field has been set.
      * @return True if the 'fechaConciliacion' field has been set, false otherwise.
      */
    public boolean hasFechaConciliacion() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'fechaConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearFechaConciliacion() {
      fechaConciliacion = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'statusConciliacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusConciliacion() {
      return statusConciliacion;
    }


    /**
      * Sets the value of the 'statusConciliacion' field.
      * @param value The value of 'statusConciliacion'.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder setStatusConciliacion(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.statusConciliacion = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'statusConciliacion' field has been set.
      * @return True if the 'statusConciliacion' field has been set, false otherwise.
      */
    public boolean hasStatusConciliacion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'statusConciliacion' field.
      * @return This builder.
      */
    public mx.baz.avro.model.liabilities.TransactionCaptacionDataConsolidated.Builder clearStatusConciliacion() {
      statusConciliacion = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionCaptacionDataConsolidated build() {
      try {
        TransactionCaptacionDataConsolidated record = new TransactionCaptacionDataConsolidated();
        record.idTipoCliente = fieldSetFlags()[0] ? this.idTipoCliente : (java.lang.Integer) defaultValue(fields()[0]);
        record.idTipoEmpresa = fieldSetFlags()[1] ? this.idTipoEmpresa : (java.lang.Integer) defaultValue(fields()[1]);
        record.plazoDias = fieldSetFlags()[2] ? this.plazoDias : (java.lang.Integer) defaultValue(fields()[2]);
        record.plazoMeses = fieldSetFlags()[3] ? this.plazoMeses : (java.lang.Integer) defaultValue(fields()[3]);
        record.codigoProductoOriginacion = fieldSetFlags()[4] ? this.codigoProductoOriginacion : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.folioConciliacion = fieldSetFlags()[5] ? this.folioConciliacion : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.fechaConciliacion = fieldSetFlags()[6] ? this.fechaConciliacion : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.statusConciliacion = fieldSetFlags()[7] ? this.statusConciliacion : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionCaptacionDataConsolidated>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionCaptacionDataConsolidated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionCaptacionDataConsolidated>
    READER$ = (org.apache.avro.io.DatumReader<TransactionCaptacionDataConsolidated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.idTipoCliente == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.idTipoCliente);
    }

    if (this.idTipoEmpresa == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.idTipoEmpresa);
    }

    out.writeInt(this.plazoDias);

    out.writeInt(this.plazoMeses);

    if (this.codigoProductoOriginacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.codigoProductoOriginacion);
    }

    if (this.folioConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.folioConciliacion);
    }

    if (this.fechaConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fechaConciliacion);
    }

    if (this.statusConciliacion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.statusConciliacion);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.idTipoCliente = null;
      } else {
        this.idTipoCliente = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.idTipoEmpresa = null;
      } else {
        this.idTipoEmpresa = in.readInt();
      }

      this.plazoDias = in.readInt();

      this.plazoMeses = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.codigoProductoOriginacion = null;
      } else {
        this.codigoProductoOriginacion = in.readString(this.codigoProductoOriginacion instanceof Utf8 ? (Utf8)this.codigoProductoOriginacion : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.folioConciliacion = null;
      } else {
        this.folioConciliacion = in.readString(this.folioConciliacion instanceof Utf8 ? (Utf8)this.folioConciliacion : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fechaConciliacion = null;
      } else {
        this.fechaConciliacion = in.readString(this.fechaConciliacion instanceof Utf8 ? (Utf8)this.fechaConciliacion : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.statusConciliacion = null;
      } else {
        this.statusConciliacion = in.readString(this.statusConciliacion instanceof Utf8 ? (Utf8)this.statusConciliacion : null);
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.idTipoCliente = null;
          } else {
            this.idTipoCliente = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.idTipoEmpresa = null;
          } else {
            this.idTipoEmpresa = in.readInt();
          }
          break;

        case 2:
          this.plazoDias = in.readInt();
          break;

        case 3:
          this.plazoMeses = in.readInt();
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.codigoProductoOriginacion = null;
          } else {
            this.codigoProductoOriginacion = in.readString(this.codigoProductoOriginacion instanceof Utf8 ? (Utf8)this.codigoProductoOriginacion : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.folioConciliacion = null;
          } else {
            this.folioConciliacion = in.readString(this.folioConciliacion instanceof Utf8 ? (Utf8)this.folioConciliacion : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fechaConciliacion = null;
          } else {
            this.fechaConciliacion = in.readString(this.fechaConciliacion instanceof Utf8 ? (Utf8)this.fechaConciliacion : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.statusConciliacion = null;
          } else {
            this.statusConciliacion = in.readString(this.statusConciliacion instanceof Utf8 ? (Utf8)this.statusConciliacion : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










